-------------------------------------------------------------------------------
-- ElvUI Additional Fonts By Crackpot (US, Thrall)
-------------------------------------------------------------------------------
local E, _, V, P, G = unpack(ElvUI)
local LSM = E.Libs.LSM

-- file automatically generated via python script
LSM:Register("font", "FantasqueSansMono Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-Bold.ttf]], 255)
LSM:Register("font", "FantasqueSansMono BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-BoldItalic.ttf]], 255)
LSM:Register("font", "FantasqueSansMono Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-Italic.ttf]], 255)
LSM:Register("font", "FantasqueSansMono Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-Regular.ttf]], 255)
LSM:Register("font", "FiraCode Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Bold.ttf]], 255)
LSM:Register("font", "FiraCode Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Light.ttf]], 255)
LSM:Register("font", "FiraCode Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Medium.ttf]], 255)
LSM:Register("font", "FiraCode Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Regular.ttf]], 255)
LSM:Register("font", "FiraCode Retina", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Retina.ttf]], 255)
LSM:Register("font", "FiraCode SemiBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-SemiBold.ttf]], 255)
LSM:Register("font", "HARRYP", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\HarryP\HARRYP__.ttf]], 255)
LSM:Register("font", "Hack Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-Bold.ttf]], 255)
LSM:Register("font", "Hack BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-BoldItalic.ttf]], 255)
LSM:Register("font", "Hack Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-Italic.ttf]], 255)
LSM:Register("font", "Hack Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-Regular.ttf]], 255)
LSM:Register("font", "Inconsolata", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inconsolata\Inconsolata.otf]], 255)
LSM:Register("font", "OpenSans Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Bold.ttf]], 255)
LSM:Register("font", "OpenSans ExtraBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-ExtraBold.ttf]], 255)
LSM:Register("font", "OpenSans Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Italic.ttf]], 255)
LSM:Register("font", "OpenSans Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Light.ttf]], 255)
LSM:Register("font", "OpenSans Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Regular.ttf]], 255)
LSM:Register("font", "OpenSans SemiBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-SemiBold.ttf]], 255)
LSM:Register("font", "PEPSI", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Pepsi\PEPSI.ttf]], 255)
LSM:Register("font", "SourceCodePro Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Black.ttf]], 255)
LSM:Register("font", "SourceCodePro Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Bold.ttf]], 255)
LSM:Register("font", "SourceCodePro ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-ExtraLight.ttf]], 255)
LSM:Register("font", "SourceCodePro Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Light.ttf]], 255)
LSM:Register("font", "SourceCodePro Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Regular.ttf]], 255)
LSM:Register("font", "SourceCodePro Semibold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Semibold.ttf]], 255)
LSM:Register("font", "SourceSansPro Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Black.ttf]], 255)
LSM:Register("font", "SourceSansPro Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Bold.ttf]], 255)
LSM:Register("font", "SourceSansPro ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-ExtraLight.ttf]], 255)
LSM:Register("font", "SourceSansPro It", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-It.ttf]], 255)
LSM:Register("font", "SourceSansPro Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Light.ttf]], 255)
LSM:Register("font", "SourceSansPro Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Regular.ttf]], 255)
LSM:Register("font", "SourceSansPro Semibold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Semibold.ttf]], 255)
LSM:Register("font", "SourceSerifPro Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Black.ttf]], 255)
LSM:Register("font", "SourceSerifPro Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Bold.ttf]], 255)
LSM:Register("font", "SourceSerifPro ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-ExtraLight.ttf]], 255)
LSM:Register("font", "SourceSerifPro It", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-It.ttf]], 255)
LSM:Register("font", "SourceSerifPro Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Light.ttf]], 255)
LSM:Register("font", "SourceSerifPro Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Regular.ttf]], 255)
LSM:Register("font", "SourceSerifPro Semibold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Semibold.ttf]], 255)
LSM:Register("font", "decterm", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\DECTerminalModern\_decterm.ttf]], 255)
LSM:Register("font", "lucon", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Lucon\lucon.ttf]], 255)
