-------------------------------------------------------------------------------
-- ElvUI Additional Fonts By Crackpot (US, Illidan)
-------------------------------------------------------------------------------
local E, _, V, P, G = unpack(ElvUI)
local LSM = E.Libs.LSM

-- file automatically generated via python script
LSM:Register("font", "AvantGarde Bold.TTF", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde\AvantGarde Bold.TTF]], 255)
LSM:Register("font", "AvantGarde Gothic Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde\AvantGarde Gothic Medium.ttf]], 255)
LSM:Register("font", "AvantGarde Italic.TTF", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde\AvantGarde Italic.TTF]], 255)
LSM:Register("font", "AvantGarde.TTF", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde\AvantGarde.TTF]], 255)
LSM:Register("font", "BADABB", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\BadaboomBB\BADABB__.ttf]], 255)
LSM:Register("font", "FantasqueSansMono Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-Bold.ttf]], 255)
LSM:Register("font", "FantasqueSansMono BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-BoldItalic.ttf]], 255)
LSM:Register("font", "FantasqueSansMono Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-Italic.ttf]], 255)
LSM:Register("font", "FantasqueSansMono Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FantasqueSansMono\FantasqueSansMono-Regular.ttf]], 255)
LSM:Register("font", "FiraCode Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Bold.ttf]], 255)
LSM:Register("font", "FiraCode Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Light.ttf]], 255)
LSM:Register("font", "FiraCode Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Medium.ttf]], 255)
LSM:Register("font", "FiraCode Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Regular.ttf]], 255)
LSM:Register("font", "FiraCode Retina", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-Retina.ttf]], 255)
LSM:Register("font", "FiraCode SemiBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\FiraCode\FiraCode-SemiBold.ttf]], 255)
LSM:Register("font", "Gilroy ExtraBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Gilroy\Gilroy-ExtraBold.otf]], 255)
LSM:Register("font", "Gilroy Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Gilroy\Gilroy-Light.otf]], 255)
LSM:Register("font", "Gotham Narrow Ultra", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Gotham Narrow Ultra\Gotham Narrow Ultra.otf]], 255)
LSM:Register("font", "Gotham XNarrow Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Gotham XNarrow Black\Gotham XNarrow Black.otf]], 255)
LSM:Register("font", "HARRYP", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\HarryP\HARRYP__.ttf]], 255)
LSM:Register("font", "Hack Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-Bold.ttf]], 255)
LSM:Register("font", "Hack BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-BoldItalic.ttf]], 255)
LSM:Register("font", "Hack Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-Italic.ttf]], 255)
LSM:Register("font", "Hack Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Hack\Hack-Regular.ttf]], 255)
LSM:Register("font", "Inconsolata", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inconsolata\Inconsolata.otf]], 255)
LSM:Register("font", "IntelOneMono Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-Bold.otf]], 255)
LSM:Register("font", "IntelOneMono BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-BoldItalic.otf]], 255)
LSM:Register("font", "IntelOneMono Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-Italic.otf]], 255)
LSM:Register("font", "IntelOneMono Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-Light.otf]], 255)
LSM:Register("font", "IntelOneMono LightItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-LightItalic.otf]], 255)
LSM:Register("font", "IntelOneMono Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-Medium.otf]], 255)
LSM:Register("font", "IntelOneMono MediumItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-MediumItalic.otf]], 255)
LSM:Register("font", "IntelOneMono Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\IntelOneMono\IntelOneMono-Regular.otf]], 255)
LSM:Register("font", "Inter Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-Black.ttf]], 255)
LSM:Register("font", "Inter Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-Bold.ttf]], 255)
LSM:Register("font", "Inter ExtraBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-ExtraBold.ttf]], 255)
LSM:Register("font", "Inter ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-ExtraLight.ttf]], 255)
LSM:Register("font", "Inter Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-Light.ttf]], 255)
LSM:Register("font", "Inter Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-Medium.ttf]], 255)
LSM:Register("font", "Inter Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-Regular.ttf]], 255)
LSM:Register("font", "Inter SemiBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-SemiBold.ttf]], 255)
LSM:Register("font", "Inter Thin", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Inter\Inter-Thin.ttf]], 255)
LSM:Register("font", "LexieReadable Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\LexieReadable\LexieReadable-Bold.ttf]], 255)
LSM:Register("font", "LexieReadable Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\LexieReadable\LexieReadable-Regular.ttf]], 255)
LSM:Register("font", "Monaco", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Monaco\Monaco.ttf]], 255)
LSM:Register("font", "Montserrat Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Black.ttf]], 255)
LSM:Register("font", "Montserrat BlackItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-BlackItalic.ttf]], 255)
LSM:Register("font", "Montserrat Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Bold.ttf]], 255)
LSM:Register("font", "Montserrat BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-BoldItalic.ttf]], 255)
LSM:Register("font", "Montserrat ExtraBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-ExtraBold.ttf]], 255)
LSM:Register("font", "Montserrat ExtraBoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-ExtraBoldItalic.ttf]], 255)
LSM:Register("font", "Montserrat ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-ExtraLight.ttf]], 255)
LSM:Register("font", "Montserrat ExtraLightItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-ExtraLightItalic.ttf]], 255)
LSM:Register("font", "Montserrat Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Italic.ttf]], 255)
LSM:Register("font", "Montserrat Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Light.ttf]], 255)
LSM:Register("font", "Montserrat LightItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-LightItalic.ttf]], 255)
LSM:Register("font", "Montserrat Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Medium.ttf]], 255)
LSM:Register("font", "Montserrat MediumItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-MediumItalic.ttf]], 255)
LSM:Register("font", "Montserrat Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Regular.ttf]], 255)
LSM:Register("font", "Montserrat SemiBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-SemiBold.ttf]], 255)
LSM:Register("font", "Montserrat SemiBoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-SemiBoldItalic.ttf]], 255)
LSM:Register("font", "Montserrat Thin", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-Thin.ttf]], 255)
LSM:Register("font", "Montserrat ThinItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Montserrat\Montserrat-ThinItalic.ttf]], 255)
LSM:Register("font", "OpenSans Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Bold.ttf]], 255)
LSM:Register("font", "OpenSans ExtraBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-ExtraBold.ttf]], 255)
LSM:Register("font", "OpenSans Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Italic.ttf]], 255)
LSM:Register("font", "OpenSans Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Light.ttf]], 255)
LSM:Register("font", "OpenSans Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-Regular.ttf]], 255)
LSM:Register("font", "OpenSans SemiBold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\OpenSans\OpenSans-SemiBold.ttf]], 255)
LSM:Register("font", "PEPSI (Modified)", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Pepsi (Modified)\PEPSI (Modified).ttf]], 255)
LSM:Register("font", "PEPSI", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Pepsi\PEPSI.ttf]], 255)
LSM:Register("font", "Roboto Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Black.ttf]], 255)
LSM:Register("font", "Roboto BlackItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-BlackItalic.ttf]], 255)
LSM:Register("font", "Roboto Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Bold.ttf]], 255)
LSM:Register("font", "Roboto BoldCondensed", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-BoldCondensed.ttf]], 255)
LSM:Register("font", "Roboto BoldCondensedItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-BoldCondensedItalic.ttf]], 255)
LSM:Register("font", "Roboto BoldItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-BoldItalic.ttf]], 255)
LSM:Register("font", "Roboto Condensed", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Condensed.ttf]], 255)
LSM:Register("font", "Roboto CondensedItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-CondensedItalic.ttf]], 255)
LSM:Register("font", "Roboto Italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Italic.ttf]], 255)
LSM:Register("font", "Roboto Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Light.ttf]], 255)
LSM:Register("font", "Roboto LightItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-LightItalic.ttf]], 255)
LSM:Register("font", "Roboto Medium", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Medium.ttf]], 255)
LSM:Register("font", "Roboto MediumItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-MediumItalic.ttf]], 255)
LSM:Register("font", "Roboto Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Regular.ttf]], 255)
LSM:Register("font", "Roboto Thin", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-Thin.ttf]], 255)
LSM:Register("font", "Roboto ThinItalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Roboto\Roboto-ThinItalic.ttf]], 255)
LSM:Register("font", "RusAvantGarde", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\RusAvantGarde\RusAvantGarde.otf]], 255)
LSM:Register("font", "SourceCodePro Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Black.ttf]], 255)
LSM:Register("font", "SourceCodePro Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Bold.ttf]], 255)
LSM:Register("font", "SourceCodePro ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-ExtraLight.ttf]], 255)
LSM:Register("font", "SourceCodePro Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Light.ttf]], 255)
LSM:Register("font", "SourceCodePro Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Regular.ttf]], 255)
LSM:Register("font", "SourceCodePro Semibold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceCodePro\SourceCodePro-Semibold.ttf]], 255)
LSM:Register("font", "SourceSansPro Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Black.ttf]], 255)
LSM:Register("font", "SourceSansPro Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Bold.ttf]], 255)
LSM:Register("font", "SourceSansPro ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-ExtraLight.ttf]], 255)
LSM:Register("font", "SourceSansPro It", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-It.ttf]], 255)
LSM:Register("font", "SourceSansPro Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Light.ttf]], 255)
LSM:Register("font", "SourceSansPro Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Regular.ttf]], 255)
LSM:Register("font", "SourceSansPro Semibold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSansPro\SourceSansPro-Semibold.ttf]], 255)
LSM:Register("font", "SourceSerifPro Black", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Black.ttf]], 255)
LSM:Register("font", "SourceSerifPro Bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Bold.ttf]], 255)
LSM:Register("font", "SourceSerifPro ExtraLight", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-ExtraLight.ttf]], 255)
LSM:Register("font", "SourceSerifPro It", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-It.ttf]], 255)
LSM:Register("font", "SourceSerifPro Light", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Light.ttf]], 255)
LSM:Register("font", "SourceSerifPro Regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Regular.ttf]], 255)
LSM:Register("font", "SourceSerifPro Semibold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\SourceSerifPro\SourceSerifPro-Semibold.ttf]], 255)
LSM:Register("font", "avantgardectt bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde CTT\avantgardectt-bold.ttf]], 255)
LSM:Register("font", "avantgardectt bolditalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde CTT\avantgardectt-bolditalic.ttf]], 255)
LSM:Register("font", "avantgardectt italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde CTT\avantgardectt-italic.ttf]], 255)
LSM:Register("font", "avantgardectt", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\AvantGarde CTT\avantgardectt.ttf]], 255)
LSM:Register("font", "coolvetica compressed rg", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Coolvetica\coolvetica compressed rg.ttf]], 255)
LSM:Register("font", "coolvetica condensed rg", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Coolvetica\coolvetica condensed rg.ttf]], 255)
LSM:Register("font", "coolvetica crammed rg", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Coolvetica\coolvetica crammed rg.ttf]], 255)
LSM:Register("font", "coolvetica rg", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Coolvetica\coolvetica rg.ttf]], 255)
LSM:Register("font", "decterm", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\DECTerminalModern\_decterm.ttf]], 255)
LSM:Register("font", "lucon", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\Lucon\lucon.ttf]], 255)
LSM:Register("font", "texgyreadventor bold", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\TeX Gyre Adventor\texgyreadventor-bold.otf]], 255)
LSM:Register("font", "texgyreadventor bolditalic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\TeX Gyre Adventor\texgyreadventor-bolditalic.otf]], 255)
LSM:Register("font", "texgyreadventor italic", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\TeX Gyre Adventor\texgyreadventor-italic.otf]], 255)
LSM:Register("font", "texgyreadventor regular", [[Interface\AddOns\ElvUI_AdditionalFonts\Fonts\TeX Gyre Adventor\texgyreadventor-regular.otf]], 255)
